### ISSUE TITLE
反向代理失效

### ISSUE THREAD

**Issue by o0NotEnded0o** [SkyDynamic/PearlTickets-Next#1]

**Comment by Goat-elegant** [comment]
![Uploading 1.png…]()

**Comment by Goat-elegant** [comment]
![Uploading 1.png…]()

**Comment by Goat-elegant** [comment]
![1](https://github.com/SkyDynamic/PearlTickets-Next/assets/95610493/9a143138-2a93-46ca-8142-fbcf0ba5ae06)
